//
// Created by Dmitri Wamback on 2026-05-31.
//

#ifndef MERIDIAN_BLOOMHORIZONTALBLURPIPELINE_H
#define MERIDIAN_BLOOMHORIZONTALBLURPIPELINE_H


class BloomHorizontalBlurPipeline {
};


#endif //MERIDIAN_BLOOMHORIZONTALBLURPIPELINE_H